### ISSUE TITLE
NextJS TurboPack resolve #node-web-compat

### ISSUE THREAD

**Issue by rickiesmooth** [awslabs/aws-jwt-verify#122] opened 2023-04-10 19:09 UTC
I'm testing turbopack with the latest version of NextJS (13.3.0) which doesn't seem to support private mappings yet. I was wondering if someone got it to work with a resolve alias?

https://turbo.build/pack/docs/features/customizing-turbopack#resolve-aliases

**Comment by ottokruse** [comment] 2023-05-02 17:05
Closing for now because unsure how to reproduce

**Closed by ottokruse** 2023-05-02 17:05 UTC
Labels: question
